services:
  mysql:
    image: mysql:latest
    container_name: hackathon-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: sefactory
      MYSQL_DATABASE: hackathon-dev
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hackathon-network
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  hackathon-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackathon-backend-dev
    networks:
      - hackathon-network
    ports:
      - "127.0.0.1:8000:8000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

networks:
  hackathon-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
